version: '3.5'

services:
  app:
   container_name: app
   build: ./
   depends_on:
      - db

   ports:
      - "8080:8080"

  db:
    image: postgres:13.1-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: westside
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
