spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    password: westside
    username: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

